{
 "title": "Jitsi Meet",
 "description": "Dashboard for Jitsi Meet Exporter",
 "tags": [ "jitsi" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jitsi_conferences, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bitrate Download",
   "type": "singlestat",
   "description": "The total incoming bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_bit_rate_download{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Bitrate Upload",
   "type": "singlestat",
   "description": "The total outgoing bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_bit_rate_upload{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "description": "The number of Java threads that the video bridge is using.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_threads{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Videostreams",
   "type": "singlestat",
   "description": "An estimation of the number of current video streams forwarded by the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_videostreams{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "singlestat",
   "description": "An average value (in milliseconds) of the RTT across all streams.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(jitsi_rtt_aggregate{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Biggest Conference",
   "type": "singlestat",
   "description": "The number of participants in the largest conference currently hosted on the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(jitsi_largest_conference{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Completed Conferences",
   "type": "singlestat",
   "description": "The sum of the lengths of all completed conferences, in seconds.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_total_conferences_created{pod=~\"$pod\"})-sum(jitsi_conferences{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Created Conferences",
   "type": "singlestat",
   "description": "The total number of conferences created on the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_total_conferences_created{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Current Participants",
   "type": "singlestat",
   "description": "The total number of participants over all JVBs",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(jitsi_participants)" }
   ]
  },
  {
   "title": "Conferences",
   "type": "graph",
   "description": "The current number of conferences.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_conferences{pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "description": "The current number of participants.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_participants{pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage of JVBs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container='jvb',pod=~\"$pod\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{container=\"jvb\", pod=~\"$pod\"}) by(pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage of JVBs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container='jvb',pod=~\"$pod\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{container='jvb', pod =~ \"$pod\"}) by(pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmitted Bytes Rate per JVB per 5 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\",interface=\"eth0\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Running JVB Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container='jvb',pod=~\"$pod\"})",
     "legendFormat": "number of pods"
    }
   ]
  }
 ]
}