apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  scope: jitsi
resources:
- web-deployment.yaml
- jicofo-deployment.yaml
- prosody-deployment.yaml
- prosody-service.yaml
- jvb/
