apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jitsi
namePrefix: shard-0-
commonLabels:
  shard: "0"
bases:
  - ../jitsi-base

patchesStrategicMerge:
  - jvb-hpa-patch.yaml
  - jvb-statefulset-patch.yaml
  - jicofo-deployment-patch.yaml
  - web-deployment-patch.yaml
  - prosody-deployment-patch.yaml
