apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  scope: jitsi
resources:
- jvb-entrypoint-configmap.yaml
- jvb-shutdown-configmap.yaml
- prosody-configmap.yaml
- web-configmap.yaml
- web-service.yaml
- common-configmap.yaml