# this is the entrypoint service for the HAProxies
apiVersion: v1
kind: Service
metadata:
  namespace: jitsi
  labels:
    service: web
  name: web
spec:
  clusterIP: None
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    k8s-app: web
